### ISSUE TITLE
Reference to admin menu permission nukes new installation: "Column 'module' cannot be null"

### ISSUE THREAD

**Issue by mazzarito** [opendevshop/devshop#556]
This error at installation: 

```
Site installation caused an exception: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'module' cannot be null [51.71 sec, 28 MB]                                                                           [error]
```

Is due to the attempted installation of the "access administration menu" permission that tries to be granted to one of the roles... Because the permission isn't defined in any of the modules, it throws a nasty exception:

```
        (
            [0] => Array
                (
                    [file] => /var/aegir/devmaster-1.x/includes/database/database.inc
                    [line] => 2227
                    [function] => execute
                    [class] => PDOStatement
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [:db_insert_placeholder_0] => 6
                                    [:db_insert_placeholder_1] => access administration menu
                                    [:db_insert_placeholder_2] => 
                                )

                        )

                )
```

Notice placeholder_2 is blank (module field). Removing the reference to the permission from these files:

- `profiles/devmaster/modules/contrib/hosting/hosting.feature.hosting.inc`
- `profiles/devmaster/modules/contrib/hosting/hosting.features.inc`

Allowed the install to proceed as normal.

**Comment by jonpugh** [comment]
Ah, this is due to a hosting.module bug... I thought it was fixed? Here's the d.o issue: https://www.drupal.org/project/hosting/issues/3020169

I removed our special 7.x-1.x-devshop branch, I was going to replace with patches.

Thanks for raising this.

**Comment by jonpugh** [comment]
I see, it was merged in December but there hasn't been an aegir release since then...

Will fix today.

**Comment by mazzarito** [comment]
I'm also having this issue, will update when i figure it out:

```
fatal: [HOST]: FAILED! => changed=true 
  cmd:
  - /usr/share/devshop/bin/devshop
  - devmaster:upgrade
  - 1.x
  - --makefile=/usr/share/devshop/build-devmaster.make
  - -n
  - --run-from-playbooks
  delta: '0:00:00.188854'
  end: '2020-03-25 20:33:35.590212'
  msg: non-zero return code
  rc: 255
  start: '2020-03-25 20:33:35.401358'
  stderr: |-
    PHP Fatal error:  Uncaught Error: Class 'Asm\Ansible\Ansible' not found in /usr/share/devshop/src/DevShop/Console/Command.php:116
    Stack trace:
    #0 /usr/share/devshop/vendor/symfony/console/Command/Command.php(221): DevShop\Console\Command->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #1 /usr/share/devshop/vendor/symfony/console/Application.php(987): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #2 /usr/share/devshop/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(DevShop\Command\DevmasterUpgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #3 /usr/share/devshop/src/DevShop/Console/Application.php(292): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Out in /usr/share/devshop/src/DevShop/Console/Command.php on line 116
  stderr_lines: <omitted>
  stdout: |2-
  
    Fatal error: Uncaught Error: Class 'Asm\Ansible\Ansible' not found in /usr/share/devshop/src/DevShop/Console/Command.php:116
    Stack trace:
    #0 /usr/share/devshop/vendor/symfony/console/Command/Command.php(221): DevShop\Console\Command->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #1 /usr/share/devshop/vendor/symfony/console/Application.php(987): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #2 /usr/share/devshop/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(DevShop\Command\DevmasterUpgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #3 /usr/share/devshop/src/DevShop/Console/Application.php(292): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Out in /usr/share/devshop/src/DevShop/Console/Command.php on line 116
```
